version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_SERVER= rabbitmq
      - RABBITMQ_DEFAULT_USER=rah
      - RABBITMQ_DEFAULT_PASS=rah
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
